# Site Settings
title: DAR-Blog
tagline: DAR-Blog
email: iker_izagirre@hotmail.com
description: >
  Blog creado para la actividad de Desarrollo de Aplicaciones en Red
#baseurl: "/mere-blog-theme"
baseurl: "/ikerizaguirre"
url: "https://ikerizaguirre.github.io"
domain: ikerizaguirre.github.io
permalink: pretty

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

#livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Iker Izaguirre Ayerregaray"
      layout: post
      image: /img/home.jpg
      show_sidebar: true
  - scope:
      path: ""
      type: "Autores"
    values:
      layout: "author"

collections:
  authors:
    output: true
# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely edit after that. If you find
# # yourself editing this file very often, consider using Jekyll's data files
# # feature for the data you need to update frequently.
# #
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# #
# # If you need help with YAML syntax, here are some quick references for you:
# # https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# # https://learnxinyminutes.com/docs/yaml/
# #
# # Site settings
# # These are used to personalize your new site. If you look in the HTML files,
# # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# # You can create any custom variable you would like, and they will be accessible
# # in the templates via {{ site.myvariable }}.

# title: Blog-DAR
# email: iker_izagirre@hotmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Blog creado para la actividad de Desarrollo de Aplicaciones en Red
# baseurl: "" # the subpath of your site, e.g. /blog
# url: https://ikerizaguirre.github.io # the base hostname & protocol for your site, e.g. http://example.com
# domain: ikerizaguirre.github.io
# twitter_username:
# github_username:

# # Build settings
# #theme: minima
# theme: mere-blog-theme
# plugins:
#   - jekyll-feed
# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/

